import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Award, ArrowLeft, Loader2, Search } from "lucide-react";
import { db, type Profile, type SocialLink } from "@/lib/bio";
import { extractBadges, PROFILE_BADGES, type ProfileBadge } from "@/lib/profileBadges";

export const Route = createFileRoute("/badges")({ component: BadgeShowcase });
const DEFINITION_PLATFORM = "__spider_badge_definition__";
function defs(links?: SocialLink[] | null) { const saved = (links ?? []).flatMap((x) => { if (x.platform !== DEFINITION_PLATFORM) return []; try { return [JSON.parse(x.icon_url || "") as ProfileBadge]; } catch { return []; } }); const map = new Map(PROFILE_BADGES.map((b) => [b.id, b])); saved.filter((b) => b?.id && b?.name).forEach((b) => map.set(b.id, b)); return [...map.values()]; }
function BadgeShowcase() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [badges, setBadges] = useState<ProfileBadge[]>(PROFILE_BADGES); const [q, setQ] = useState(""); const [busy, setBusy] = useState(true);
  useEffect(() => { void db.from("profiles").select("*").order("created_at", { ascending: false }).limit(500).then(({ data }) => { const rows = (data ?? []) as Profile[]; setProfiles(rows); setBadges(defs(rows.find((p) => p.id)?.social_links)); setBusy(false); }); }, []);
  const counts = useMemo(() => { const m = new Map<string, number>(); profiles.forEach((p) => extractBadges(p.social_links).forEach((b) => m.set(b.id, (m.get(b.id) || 0) + 1))); return m; }, [profiles]);
  const visible = badges.filter((b) => `${b.name} ${b.description}`.toLowerCase().includes(q.toLowerCase()));
  if (busy) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div>;
  return <div className="min-h-screen bg-[#070707] text-white"><header className="border-b border-white/10 bg-black/70 px-4 py-5 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><Link to="/" className="btn-ghost"><ArrowLeft className="h-4 w-4" /> Home</Link><div className="text-center"><h1 className="font-display text-2xl font-bold">Badge Showcase</h1><p className="text-xs text-white/45">Explore every badge available on Spider Wensors</p></div><div className="w-16" /></div></header><main className="mx-auto max-w-6xl px-4 py-7"><div className="mx-auto mb-6 flex max-w-md items-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2"><Search className="h-4 w-4 text-white/40" /><input className="w-full bg-transparent text-sm outline-none" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search badges…" /></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((b) => <article key={b.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5" style={{ boxShadow: `0 0 18px ${b.glowColor || b.color}25` }}><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl border" style={{ color: b.color, borderColor: `${b.glowColor || b.color}80`, boxShadow: `0 0 12px ${b.glowColor || b.color}70, 0 0 30px ${b.glowColor || b.color}35` }}>{b.imageUrl ? <img src={b.imageUrl} alt="" className="h-9 w-9 object-contain" /> : b.emoji ? <span className="text-2xl">{b.emoji}</span> : <Award className="h-8 w-8" />}</div><div><h2 className="font-display text-lg font-bold">{b.name}</h2><p className="mt-1 text-xs text-white/45">{b.description}</p></div></div><div className="mt-4 text-[11px] font-semibold text-white/40">{counts.get(b.id) || 0} player{counts.get(b.id) === 1 ? "" : "s"} assigned</div></article>)}</div></main></div>;
}
