import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Palette, Sparkles, Type, LayoutTemplate, Boxes, Share2, Save } from "lucide-react";
import { toast } from "sonner";
import { db, type Profile } from "@/lib/bio";
import { useAuth, useMyProfile } from "@/hooks/useAuth";
import { DEFAULT_PROFILE_CUSTOMIZATION, normalizeProfileCustomization, type ProfileCustomization } from "@/lib/profileCustomization";

export const Route = createFileRoute("/customization")({
  head: () => ({ meta: [{ title: "Profile Customization — Spider Website" }, { name: "robots", content: "noindex" }] }),
  component: Customization,
});

type Section = "layout" | "appearance" | "effects" | "widgets" | "typography" | "seo";
const inputClass = "w-full rounded-xl border border-white/10 bg-white/[0.035] px-3.5 py-3 text-sm text-white outline-none transition focus:border-red-500/50 focus:bg-white/[0.05]";

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block text-xs font-medium text-white/60"><span className="mb-1.5 block">{label}</span>{children}</label>;
}

function Customization() {
  const navigate = useNavigate();
  const { user, loading } = useAuth();
  const { profile, loading: profileLoading } = useMyProfile(user?.id);
  const [section, setSection] = useState<Section>("appearance");
  const [config, setConfig] = useState<ProfileCustomization>(DEFAULT_PROFILE_CUSTOMIZATION);
  const [saving, setSaving] = useState(false);

  useEffect(() => { if (!loading && !user) navigate({ to: "/auth" }); }, [loading, user, navigate]);
  useEffect(() => { if (profile) setConfig(normalizeProfileCustomization((profile as Profile & { profile_settings?: unknown }).profile_settings)); }, [profile]);

  const update = <K extends keyof ProfileCustomization>(key: K, value: ProfileCustomization[K]) => setConfig(c => ({ ...c, [key]: value }));
  const save = async () => {
    if (!profile) return;
    setSaving(true);
    const { error } = await db.from("profiles").update({ profile_settings: config } as any).eq("id", profile.id);
    setSaving(false);
    if (error) toast.error(error.message || "Could not save customization"); else toast.success("Customization saved");
  };

  const widgetTypes = useMemo(() => ["Discord Presence", "Now Playing", "YouTube", "GitHub", "Weather", "Timezone", "Profile Stats", "Music Player", "About Me", "Projects", "Skills"], []);
  const nav: Array<[Section, string, typeof Palette]> = [["layout", "Layout", LayoutTemplate], ["appearance", "Appearance", Palette], ["effects", "Effects", Sparkles], ["widgets", "Widgets", Boxes], ["typography", "Typography", Type], ["seo", "SEO & Sharing", Share2]];

  if (loading || profileLoading) return <div className="min-h-screen grid place-items-center bg-[#070707] text-white/60">Loading…</div>;
  return <div className="min-h-screen bg-[#070707] text-white">
    <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:py-8">
      <header className="mb-6 flex items-center justify-between gap-3">
        <div className="flex items-center gap-3"><Link to="/dashboard" className="rounded-xl border border-white/10 bg-white/[0.025] p-2.5 text-white/60 transition hover:bg-white/[0.06] hover:text-white"><ArrowLeft className="h-4 w-4" /></Link><div><h1 className="text-xl font-bold tracking-tight"><span className="text-red-500">Spider</span> Website Customization</h1><p className="mt-0.5 text-xs text-white/40">Build your profile exactly the way you want it.</p></div></div>
        <button onClick={() => void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-red-500 px-4 py-2.5 text-sm font-semibold transition hover:bg-red-400 disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save"}</button>
      </header>
      <div className="grid gap-5 lg:grid-cols-[210px_1fr]">
        <aside className="h-fit rounded-2xl border border-white/10 bg-white/[0.025] p-2">{nav.map(([id,label,Icon]) => <button key={id} onClick={() => setSection(id)} className={`mb-1 flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm transition ${section === id ? "bg-red-500/10 text-red-300" : "text-white/60 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4 w-4" />{label}</button>)}</aside>
        <main className="rounded-2xl border border-white/10 bg-white/[0.025] p-5 sm:p-7">
          {section === "layout" && <div className="space-y-6"><div><h2 className="text-lg font-bold tracking-tight">Profile layout</h2><p className="mt-1 text-sm text-white/45">Choose the structure of your public profile.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(["default","modern","minimal","sleek","portfolio"] as const).map(layout => <button key={layout} onClick={() => update("layout", layout)} className={`rounded-2xl border p-4 text-left transition ${config.layout === layout ? "border-red-500/50 bg-red-500/10" : "border-white/10 bg-black/20 hover:bg-white/[0.04]"}`}><div className="font-semibold capitalize">{layout}</div><div className="mt-1 text-xs text-white/40">{layout === "portfolio" ? "About, projects and skills" : "Custom profile presentation"}</div>{config.layout === layout && <Check className="mt-3 h-4 w-4 text-red-400" />}</button>)}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="Banner URL"><input className={inputClass} value={config.bannerUrl} onChange={e => update("bannerUrl", e.target.value)} placeholder="https://…" /></Field><Field label="Location"><input className={inputClass} value={config.location} onChange={e => update("location", e.target.value)} placeholder="Your location" /></Field></div><label className="flex items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={config.showLocation} onChange={e => update("showLocation", e.target.checked)} /> Show location on profile</label></div>}
          {section === "appearance" && <div className="space-y-6"><div><h2 className="text-lg font-bold tracking-tight">Appearance</h2><p className="mt-1 text-sm text-white/45">Control card styling, borders, colors, avatar shape and glow.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Border color"><input type="color" className="h-11 w-full rounded-xl bg-black/20" value={config.borderColor} onChange={e => update("borderColor", e.target.value)} /></Field><Field label="Text color"><input type="color" className="h-11 w-full rounded-xl bg-black/20" value={config.textColor} onChange={e => update("textColor", e.target.value)} /></Field><Field label="Icon color"><input type="color" className="h-11 w-full rounded-xl bg-black/20" value={config.iconColor} onChange={e => update("iconColor", e.target.value)} /></Field><Field label={`Border width · ${config.borderWidth}px`}><input type="range" min="0" max="8" value={config.borderWidth} onChange={e => update("borderWidth", +e.target.value)} className="w-full accent-red-500" /></Field><Field label={`Border opacity · ${Math.round(config.borderOpacity*100)}%`}><input type="range" min="0" max="1" step="0.01" value={config.borderOpacity} onChange={e => update("borderOpacity", +e.target.value)} className="w-full accent-red-500" /></Field><Field label={`Avatar radius · ${config.avatarRadius}px`}><input type="range" min="0" max="999" value={config.avatarRadius} onChange={e => update("avatarRadius", +e.target.value)} className="w-full accent-red-500" /></Field><Field label={`Card radius · ${config.borderRadius}px`}><input type="range" min="0" max="60" value={config.borderRadius} onChange={e => update("borderRadius", +e.target.value)} className="w-full accent-red-500" /></Field><Field label={`Glow size · ${config.profileGlowSize}px`}><input type="range" min="0" max="80" value={config.profileGlowSize} onChange={e => update("profileGlowSize", +e.target.value)} className="w-full accent-red-500" /></Field><Field label="Card gradient color"><input type="color" className="h-11 w-full rounded-xl bg-black/20" value={config.cardGradientColor} onChange={e => update("cardGradientColor", e.target.value)} /></Field></div><div className="grid gap-3 sm:grid-cols-2">{[["borderGlow","Border glow"],["profileGlow","Profile glow"],["cardGradientEnabled","Card gradient"],["monochromeIcons","Monochrome icons"],["showSocials","Show socials"]].map(([key,label]) => <label key={key} className="flex items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={Boolean(config[key as keyof ProfileCustomization])} onChange={e => update(key as keyof ProfileCustomization, e.target.checked as never)} />{label}</label>)}</div><Field label="Social alignment"><select className={inputClass} value={config.socialAlignment} onChange={e => update("socialAlignment", e.target.value as ProfileCustomization["socialAlignment"])}>{["left","center","right"].map(x => <option key={x}>{x}</option>)}</select></Field></div>}
          {section === "effects" && <div className="space-y-6"><div><h2 className="text-lg font-bold tracking-tight">Effects</h2><p className="mt-1 text-sm text-white/45">Add motion and atmosphere without changing your core profile design.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Username effect"><select className={inputClass} value={config.usernameEffect} onChange={e => update("usernameEffect", e.target.value as ProfileCustomization["usernameEffect"])}>{["none","glow","pulse","gradient","typing"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Background effect"><select className={inputClass} value={config.backgroundEffect} onChange={e => update("backgroundEffect", e.target.value as ProfileCustomization["backgroundEffect"])}>{["none","particles","stars","aurora","grid","scanlines"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Cursor effect"><select className={inputClass} value={config.cursorEffect} onChange={e => update("cursorEffect", e.target.value as ProfileCustomization["cursorEffect"])}>{["none","glow","spark"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Typewriter speed"><input type="range" min="20" max="200" value={config.typewriterSpeed} onChange={e => update("typewriterSpeed", +e.target.value)} className="w-full accent-red-500" /></Field></div><label className="flex items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={config.animatedTitle} onChange={e => update("animatedTitle", e.target.checked)} /> Animated page title</label></div>}
          {section === "widgets" && <div className="space-y-6"><div><h2 className="text-lg font-bold tracking-tight">Widgets & sections</h2><p className="mt-1 text-sm text-white/45">Choose profile modules and portfolio content.</p></div><div className="grid gap-2 sm:grid-cols-2">{widgetTypes.map(type => { const id = type.toLowerCase().replace(/[^a-z0-9]+/g,"-"); const active = config.widgets.some(w => w.id === id && w.enabled); return <button key={id} onClick={() => update("widgets", active ? config.widgets.filter(w => w.id !== id) : [...config.widgets,{id,type,enabled:true}])} className={`flex items-center justify-between rounded-xl border px-4 py-3 text-left text-sm transition ${active ? "border-red-500/40 bg-red-500/10" : "border-white/10 bg-black/20 hover:bg-white/[0.04]"}`}><span>{type}</span>{active && <Check className="h-4 w-4 text-red-400" />}</button>; })}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="About Me"><textarea className={`${inputClass} min-h-28`} value={config.aboutMe} onChange={e => update("aboutMe", e.target.value)} /></Field><Field label="Second tab content"><textarea className={`${inputClass} min-h-28`} value={config.secondTabContent} onChange={e => update("secondTabContent", e.target.value)} /></Field></div><label className="flex items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={config.secondTabEnabled} onChange={e => update("secondTabEnabled", e.target.checked)} /> Enable second profile tab</label></div>}
          {section === "typography" && <div className="space-y-6"><div><h2 className="text-lg font-bold tracking-tight">Typography</h2><p className="mt-1 text-sm text-white/45">Match your profile text with your own font and typewriter style.</p></div><Field label="Font family"><input className={inputClass} value={config.customFont} onChange={e => update("customFont", e.target.value)} placeholder="Inter, Poppins, …" /></Field><Field label="Typewriter lines"><textarea className={`${inputClass} min-h-32`} value={config.typewriterTexts.join("\n")} onChange={e => update("typewriterTexts", e.target.value.split("\n").map(x => x.trim()).filter(Boolean).slice(0,10))} placeholder="Developer\nCreator\nMinecraft player" /></Field></div>}
          {section === "seo" && <div className="space-y-6"><div><h2 className="text-lg font-bold tracking-tight">SEO & sharing</h2><p className="mt-1 text-sm text-white/45">Control the browser title and social preview metadata for your profile.</p></div><Field label="Browser/page title"><input className={inputClass} value={config.seoTitle} onChange={e => update("seoTitle", e.target.value)} /></Field><Field label="Description"><textarea className={`${inputClass} min-h-24`} value={config.seoDescription} onChange={e => update("seoDescription", e.target.value)} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Social preview image"><input className={inputClass} value={config.seoImage} onChange={e => update("seoImage", e.target.value)} placeholder="https://…" /></Field><Field label="Favicon URL"><input className={inputClass} value={config.faviconUrl} onChange={e => update("faviconUrl", e.target.value)} placeholder="https://…" /></Field></div><Field label="Page alias"><input className={inputClass} value={config.pageAlias} onChange={e => update("pageAlias", e.target.value)} placeholder="my-page" /></Field></div>}
        </main>
      </div>
    </div>
  </div>;
}
