/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BadgeStudioRouteImport } from './routes/badge-studio'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AdminBadgesRouteImport } from './routes/admin-badges'
import { Route as AdminBadgesBadgeIdRouteImport } from './routes/admin-badges/$badgeId'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const UsernameRoute = UsernameRouteImport.update({ id: '/$username', path: '/$username', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const ClaimRoute = ClaimRouteImport.update({ id: '/claim', path: '/claim', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const BadgeStudioRoute = BadgeStudioRouteImport.update({ id: '/badge-studio', path: '/badge-studio', getParentRoute: () => rootRouteImport } as any)
const BadgesRoute = BadgesRouteImport.update({ id: '/badges', path: '/badges', getParentRoute: () => rootRouteImport } as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({ id: '/admin-badges', path: '/admin-badges', getParentRoute: () => rootRouteImport } as any)
const AdminBadgesBadgeIdRoute = AdminBadgesBadgeIdRouteImport.update({ id: '/admin-badges/$badgeId', path: '/$badgeId', getParentRoute: () => AdminBadgesRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/dashboard': typeof DashboardRoute
  '/badge-studio': typeof BadgeStudioRoute
  '/badges': typeof BadgesRoute
  '/admin-badges': typeof AdminBadgesRoute
  '/admin-badges/$badgeId': typeof AdminBadgesBadgeIdRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/dashboard': typeof DashboardRoute
  '/badge-studio': typeof BadgeStudioRoute
  '/badges': typeof BadgesRoute
  '/admin-badges': typeof AdminBadgesRoute
  '/admin-badges/$badgeId': typeof AdminBadgesBadgeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$username' | '/admin' | '/auth' | '/claim' | '/dashboard' | '/badge-studio' | '/badges' | '/admin-badges' | '/admin-badges/$badgeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$username' | '/admin' | '/auth' | '/claim' | '/dashboard' | '/badge-studio' | '/badges' | '/admin-badges' | '/admin-badges/$badgeId'
  id: '__root__' | '/' | '/$username' | '/admin' | '/auth' | '/claim' | '/dashboard' | '/badge-studio' | '/badges' | '/admin-badges' | '/admin-badges/$badgeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClaimRoute: typeof ClaimRoute
  DashboardRoute: typeof DashboardRoute
  BadgeStudioRoute: typeof BadgeStudioRoute
  BadgesRoute: typeof BadgesRoute
  AdminBadgesRoute: typeof AdminBadgesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/$username': { id: '/$username'; path: '/$username'; fullPath: '/$username'; preLoaderRoute: typeof UsernameRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/claim': { id: '/claim'; path: '/claim'; fullPath: '/claim'; preLoaderRoute: typeof ClaimRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/badge-studio': { id: '/badge-studio'; path: '/badge-studio'; fullPath: '/badge-studio'; preLoaderRoute: typeof BadgeStudioRouteImport; parentRoute: typeof rootRouteImport }
    '/badges': { id: '/badges'; path: '/badges'; fullPath: '/badges'; preLoaderRoute: typeof BadgesRouteImport; parentRoute: typeof rootRouteImport }
    '/admin-badges': { id: '/admin-badges'; path: '/admin-badges'; fullPath: '/admin-badges'; preLoaderRoute: typeof AdminBadgesRouteImport; parentRoute: typeof rootRouteImport }
    '/admin-badges/$badgeId': { id: '/admin-badges/$badgeId'; path: '/$badgeId'; fullPath: '/admin-badges/$badgeId'; preLoaderRoute: typeof AdminBadgesBadgeIdRouteImport; parentRoute: typeof AdminBadgesRoute }
  }
}
const rootRouteChildren: RootRouteChildren = { IndexRoute, UsernameRoute, AdminRoute, AuthRoute, ClaimRoute, DashboardRoute, BadgeStudioRoute, BadgesRoute, AdminBadgesRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
